# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

make_V_star <- function(Z, Z0, Z1, wtr) {
    .Call(`_didimputation_make_V_star`, Z, Z0, Z1, wtr)
}

